<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tabariyya</groupId>
    <artifactId>spring-jwt</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>2.7.18</spring-boot.version>
    </properties>

    <name>com.tabariyya</name>
    <description>SynCache Binding For Java</description>
    <url>https://github.com/tabariyya/synCache-java.git</url>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>Waleed</id>
            <name>Waleed Shanaa</name>
            <email>waleed.shanaa@tabariyya.com</email>
        </developer>
    </developers>

    <scm>
        <url>https://github.com/tabariyya/synCache-java</url>
        <connection>scm:git:git://github.com/tabariyya/synCache-java.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:tabariyya/synCache-java.git</developerConnection>
    </scm>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- Spring AOP for @Aspect / @Around -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Spring Web for HttpServletRequest, Filter, RequestContextHolder -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.tabariyya</groupId>
            <artifactId>utils</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>


</project>
